/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*
 * LED_PushPull.c
 *
 *  Created on: 28-Feb-2026
 *      Author: junaid
 */

#include "STM32F40xx.h"

void delay()
{
	for(uint32_t i = 0; i < 1000000; i++);
}

int main(void)
{
	GPIO_Handle_t BlueLed;
	GPIO_Handle_t RedLed;
	GPIO_Handle_t OrangeLed;
	GPIO_Handle_t GreenLed;

	GreenLed.pGPIOx = GPIOD;
	GreenLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GreenLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GreenLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GreenLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GreenLed.GPIO_PinConfig.GPIO_PinPupControl = GPIO_NO_PUPD;

	OrangeLed.pGPIOx = GPIOD;
	OrangeLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	OrangeLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	OrangeLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	OrangeLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	OrangeLed.GPIO_PinConfig.GPIO_PinPupControl = GPIO_NO_PUPD;

	RedLed.pGPIOx = GPIOD;
	RedLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	RedLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	RedLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	RedLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	RedLed.GPIO_PinConfig.GPIO_PinPupControl = GPIO_NO_PUPD;

	BlueLed.pGPIOx = GPIOD;
	BlueLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	BlueLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	BlueLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	BlueLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	BlueLed.GPIO_PinConfig.GPIO_PinPupControl = GPIO_NO_PUPD;

	GPIO_Init(&GreenLed);
	GPIO_Init(&OrangeLed);
	GPIO_Init(&RedLed);
	GPIO_Init(&BlueLed);
	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
		delay();
	}
	return 0;
}
